apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: jamph-umami-frontend-dev
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  envFrom:
  - secret: student-bigquery
  env:
    - name: RAG_API_URL
      value: "http://jamph-rag-api-umami-dev"
  accessPolicy:
    outbound:
      rules:
        - application: jamph-rag-api-umami-dev
          namespace: team-researchops
  liveness:
    path: /isalive
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://jamph.ekstern.dev.nav.no
