apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: jamph-umami-frontend
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  envFrom:
  - secret: student-bigquery-prod
  env:
    - name: RAG_API_URL
      value: "http://jamph-rag-api-umami"
  accessPolicy:
    outbound:
      rules:
        - application: jamph-rag-api-umami
          namespace: team-researchops
  liveness:
    path: /isalive
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  ingresses:
    - https://jamph.ansatt.nav.no
